### ISSUE TITLE
check_plugins.js fails against AWS hosted Elasticsearch.

### ISSUE THREAD

**Issue by mrburrito** [pelias/schema#213]
I'm running a managed Elasticsearch 2.3 cluster in AWS to host Pelias. I'm trying to get it up and running and the `create_index.js` script fails when checking for the required plugins:

```bash
/home/pelias/schema/scripts/check_plugins.js:40
      var isInstalled = !!node.plugins.filter( function( installedPlugin ){
                                      ^

TypeError: Cannot read property 'filter' of undefined
    at /home/pelias/schema/scripts/check_plugins.js:40:39
    at Array.forEach (native)
    at /home/pelias/schema/scripts/check_plugins.js:37:13
    at respond (/home/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:310:9)
    at checkRespForFailure (/home/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/home/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/home/pelias/schema/node_modules/lodash/lodash.js:4968:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
please install mandatory plugins before continuing.
```

Running through the commands in the console, I definitely see that the `plugins` property is not returned by the Elasticsearch client when it retrieves the node metadata.

I'm running off the `production` branch, against an AWS managed Elasticsearch 2.3.2 cluster. I'm using the [aws-signing-proxy](https://hub.docker.com/r/cllunsford/aws-signing-proxy/) container to sign requests to my cluster so Pelias is using its default `localhost:9200` host for Elasticsearch.

**Comment by orangejulius** [comment]
Hey @mrburrito,
Thanks for writing in. I just pushed https://github.com/pelias/schema/pull/214, which should fix this problem. We noticed it a long time ago when checking out the hosted Elasticsearch service, but didn't fix it (doh!).

It's worth noting that in our testing the hosted Elasticsearch service was [noticeably slower](https://github.com/pelias/pelias/issues/402#issuecomment-255854624) than using standard EC2 instances, so if you encounter any issues there keep that in mind.

If you could test out that branch and let us know how it works, we'll merge it right away!

**Comment by mrburrito** [comment]
Yep! That looks like it worked. Thanks! And thanks for the info on performance.

FYI - if you wanted to verify (which probably isn't necessary since AWS supports the plugin you need), the `/_cat/plugins` call returns all the info you'd need:

```bash
$ curl localhost:9200/_cat/plugins
Hamilton Slade analysis-icu        2.3.2 j
Hamilton Slade analysis-kuromoji   2.3.2 j
Hamilton Slade analysis-phonetic   2.3.2 j
Hamilton Slade cloud-aws           2.3.2 j
Hamilton Slade elasticsearch-jetty 2.2.0 j
Hamilton Slade kibana              2.3.2 s /_plugin/kibana/
Cyclops        analysis-icu        2.3.2 j
Cyclops        analysis-kuromoji   2.3.2 j
Cyclops        analysis-phonetic   2.3.2 j
Cyclops        cloud-aws           2.3.2 j
Cyclops        elasticsearch-jetty 2.2.0 j
Cyclops        kibana              2.3.2 s /_plugin/kibana/
Vidar          analysis-icu        2.3.2 j
Vidar          analysis-kuromoji   2.3.2 j
Vidar          analysis-phonetic   2.3.2 j
Vidar          cloud-aws           2.3.2 j
Vidar          elasticsearch-jetty 2.2.0 j
Vidar          kibana              2.3.2 s /_plugin/kibana/
Ahmet Abdol    analysis-icu        2.3.2 j
Ahmet Abdol    analysis-kuromoji   2.3.2 j
Ahmet Abdol    analysis-phonetic   2.3.2 j
Ahmet Abdol    cloud-aws           2.3.2 j
Ahmet Abdol    elasticsearch-jetty 2.2.0 j
Ahmet Abdol    kibana              2.3.2 s /_plugin/kibana/
Man-Killer     analysis-icu        2.3.2 j
Man-Killer     analysis-kuromoji   2.3.2 j
Man-Killer     analysis-phonetic   2.3.2 j
Man-Killer     cloud-aws           2.3.2 j
Man-Killer     elasticsearch-jetty 2.2.0 j
Man-Killer     kibana              2.3.2 s /_plugin/kibana/
Bushmaster     analysis-icu        2.3.2 j
Bushmaster     analysis-kuromoji   2.3.2 j
Bushmaster     analysis-phonetic   2.3.2 j
Bushmaster     cloud-aws           2.3.2 j
Bushmaster     elasticsearch-jetty 2.2.0 j
Bushmaster     kibana              2.3.2 s /_plugin/kibana/
Vermin         analysis-icu        2.3.2 j
Vermin         analysis-kuromoji   2.3.2 j
Vermin         analysis-phonetic   2.3.2 j
Vermin         cloud-aws           2.3.2 j
Vermin         elasticsearch-jetty 2.2.0 j
Vermin         kibana              2.3.2 s /_plugin/kibana/
```
